/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://u73yjae7tnd75m442vuqqcgutq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-4y3tlcg7urac7gce6l55wgdyxi",
    "aws_cognito_identity_pool_id": "us-east-1:19ff5170-98e5-4feb-a370-26f842c28ee3",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_z7R2CxnlD",
    "aws_user_pools_web_client_id": "2td5iaofotjemphisgf9ci1rvr",
    "oauth": {}
};


export default awsmobile;
